# Install and configure Rust programming language
# File: roles/rust/tasks/main.yml
---
- name: Install AWS CLI
  community.general.homebrew:
    name: awscli
    state: present
  register: app_install

- name: Copy AWS CLI environment configuration
  ansible.builtin.copy:
    src: aws.zsh
    dest: "$HOME/.oh-my-zsh/custom/aws.zsh"
    mode: '0644'
  register: env_config

# -----------------------------------------------------------------------------
# AWS CLI configuration
# -----------------------------------------------------------------------------
- name: Ensure AWS CLI directory exists
  file:
    path: "{{ ansible_env.HOME }}/.aws/cli"
    state: directory
    mode: '0755'
  register: aws_dir_create

- name: Clone awscli-aliases repository
  ansible.builtin.git:
    repo: https://github.com/awslabs/awscli-aliases.git
    dest: /tmp/awscli-aliases
    version: master
    force: yes
  register: aliases_clone

- name: Copy alias file to AWS CLI directory
  ansible.builtin.copy:
    src: /tmp/awscli-aliases/alias
    dest: "{{ ansible_env.HOME }}/.aws/cli/alias"
    mode: '0644'
    remote_src: yes
  register: aliases_install

# -----------------------------------------------------------------------------
# AWS EC2 Instance Selector
# -----------------------------------------------------------------------------
- name: Add AWS tap for additional tools
  community.general.homebrew_tap:
    name: aws/tap
    state: present
  register: aws_tap

- name: Install EC2 Instance Selector
  community.general.homebrew:
    name: aws/tap/ec2-instance-selector
    state: present
  register: ec2_selector_install


- name: Clean up temporary clone
  ansible.builtin.file:
    path: /tmp/awscli-aliases
    state: absent

- name: Display AWS CLI setup status
  debug:
    msg:
      - "AWS CLI setup completed:"
      - "  - Package: {% if app_install.changed %}installed{% else %}already present{% endif %}"
      - "  - AWS directory: {% if aws_dir_create.changed %}created{% else %}already exists{% endif %}"
      - "  - Clone awscli-aliases: {% if aliases_clone.changed %}cloned{% else %}already exists{% endif %}"
      - "  - Shell config: {% if env_config.changed %}deployed{% else %}already present{% endif %}"
      - "  - AWS CLI aliases: {% if aliases_install.changed %}installed{% else %}already present{% endif %} at ~/.aws/cli/alias"
      - "AWS EC2 Instance Selector setup completed:"
      - "  - AWS tap: {% if aws_tap.changed %}added{% else %}already present{% endif %}"
      - "  - EC2 Instance Selector: {% if ec2_selector_install.changed %}installed{% else %}already present{% endif %}"
